### ISSUE TITLE
Sending notification from phone using MMM-remote-control

### ISSUE THREAD

**Issue by arekcygan** [MunichStef/MMM_Webradio#1]
Hi,

I really like your mode and I always wanted to use a similar functionality in my magic mirror. There is just one thing that I couldn't figured out. How to modify MMM-remote-control to be able to control MMM_Webradio? Can you please advise?

**Comment by arekcygan** [comment]
Ha! I figured it out. It can be done simply by entering below url:

http://XXX.XXX.X.XXX:8080/remote?action=NOTIFICATION&notification=WEBRADIO_ONOFF

However it would be even better if we could add some controls to MMM remote control module.

**Comment by MunichStef** [comment]
Hi!
Thanks for your feedback. In general all you need to do from ANY module is to send a notification with the notification itself beeing:
- "WEBRADIO_ONOFF"
- "WEBRADIO_VOLUP"
- "WEBRADIO_VOLDOWN"
- "WEBRADIO_NEXT"
- "WEBRADIO_PREV"

**Comment by arekcygan** [comment]
Hi thank you for your answer. Basically I know that above notifications needs to be send. Now I struggling how to adjust remote.html and remote.js in order to create custom menu that will allow me to control the web radio.

**Comment by arekcygan** [comment]
Ok so this is what I have right now: 

https://github.com/Jopyth/MMM-Remote-Control/issues/94#issuecomment-436220700

It's working but it's opening a new web browser every time I'm sending the notification.

**Comment by MunichStef** [comment]
If it's ok for you I'd close this issue. It's more a topic for the Remote Control module unless my module does something wrong / something you would not expect / something you would like to be different?

**Comment by arekcygan** [comment]
It's ok - please close it. Thank's for creating a very nice radio :).
